### ISSUE TITLE
Handle corrupted database in sqlite

### ISSUE THREAD

**Issue by ricardobrg** [tiki/core-trail-endpoint#325]
This error happened during offer acceptance. The only fix is to removed the database and reinitialize TIKI SDK.

```
Uncaught SqliteException(11): while executing, database disk image is malformed, database disk image is malformed (code 11)
  Causing statement:     CREATE TABLE IF NOT EXISTS txn (
      id BLOB PRIMARY KEY NOT NULL,
      merkel_proof BLOB,
      version INTEGER NOT NULL,
      address BLOB NOT NULL,
      contents BLOB NOT NULL,
      asset_ref TEXT NOT NULL,
      block_id BLOB, 
      timestamp INTEGER NOT NULL,
      user_signature BlOB NOT NULL,
      app_signature BlOB,
      FOREIGN KEY(block_id) 
        REFERENCES block(id)
     ); 
    , parameters: 
    at Object.d (https://unpkg.com/@mytiki/tiki-sdk-js@2.1.4/dist/index.js:1:12959)
    at Object.A5 (https://unpkg.com/@mytiki/tiki-sdk-js@2.1.4/dist/index.js:1:153256)
    at rc.c0 (https://unpkg.com/@mytiki/tiki-sdk-js@2.1.4/dist/index.js:1:519417)
    at rc.cz (https://unpkg.com/@mytiki/tiki-sdk-js@2.1.4/dist/index.js:1:519557)
    at https://unpkg.com/@mytiki/tiki-sdk-js@2.1.4/dist/index.js:1:143764
    at G.a (https://unpkg.com/@mytiki/tiki-sdk-js@2.1.4/dist/index.js:1:42343)
    at zE.$2 (https://unpkg.com/@mytiki/tiki-sdk-js@2.1.4/dist/index.js:1:188691)
    at zp.$1 (https://unpkg.com/@mytiki/tiki-sdk-js@2.1.4/dist/index.js:1:188587)
    at z2.v4 (https://unpkg.com/@mytiki/tiki-sdk-js@2.1.4/dist/index.js:1:200965)
    at z2.jk (https://unpkg.com/@mytiki/tiki-sdk-js@2.1.4/dist/index.js:1:201017)
```
My suspicious is that the user leaves the page during database creation and the script stops, breaking the database creation.

**Comment by ricardobrg** [comment]
Transfering this issue to Trail because it should be treated in the origin.
Since the database is for local caching, in theory it can be dropped if any inconsistency is found. 
To be discussed.
